server:
  port: 8080

spring:
  application:
    name: cards-challenge
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

feign:
  okhttp:
    enabled: true

ehcache:
  playersCache:
    cacheName: "playersCache"
    heapEntries: 1
    timeToLiveInSeconds: 0 # "forever"
  cardCache:
    cacheName: "cardCache"
    heapEntries: 26
    timeToLiveInSeconds: 0 # "forever"